name: Run ubbd tests on Centos-8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:8

    steps:
    - uses: actions/checkout@v2
    - name: run_check
      run: yum install sudo -y; sudo ./run_ubbd_tests.sh
