name: Run integration tests on ubuntu-20.04

on:
  pull_request:
    types: [labeled]
    labels:
      - name: integration-tests
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Add SSH key to known_hosts
      run: ssh-keyscan datatravelguide.yds.life >> ~/.ssh/known_hosts
      
    - name: SSH into server
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@datatravelguide.yds.life "echo 'Hello, world!'"
