name: Run integration tests on ubuntu-20.04

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add SSH key to known_hosts
      run: ssh-keyscan datatravelguide.yds.life >> ~/.ssh/known_hosts
      
    - name: SSH into server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        echo "secrets.SSH_PRIVATE_KEY: "
        echo ${{ secrets.SSH_PRIVATE_KEY }}
        echo $SSH_PRIVATE_KEY
        ssh -i "$SSH_PRIVATE_KEY" -p $SSH_PORT $SSH_USERNAME@datatravelguide.yds.life "echo 'Hello, world!'"
