name: Run integration tests on ubuntu

on:
  pull_request_target:
    types: [opened, synchronize, labeled]
    labels:
      - name: integration-tests
jobs:
  integration-tests:
    runs-on: self-hosted
    timeout-minutes: 4320

    environment: integration-tests
    steps:
    - uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add SSH key to known_hosts
      run: ssh-keyscan datatravelguide.yds.life >> ~/.ssh/known_hosts

    - name: SSH into server
      timeout-minutes: 4000
      env:
        PASSWORD: ${{ secrets.SSH_PASSWORD }}
        PORT: ${{ secrets.SSH_PORT }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
      run: |
        sshpass -p ${PASSWORD} ssh -o TCPKeepAlive=yes -o ServerAliveInterval=120 -o ServerAliveCountMax=9999 -o StrictHostKeyChecking=no -p ${PORT} ${USERNAME}@${HOSTNAME} "./run-ubbd-integration-tests.sh ${{github.event.pull_request.head.ref}} ${{github.event.pull_request.head.repo.full_name}} > output"
        touch output
        tail -f output &
        while true; do
          sshpass -p ${PASSWORD} scp -P ${PORT} ${USERNAME}@${HOSTNAME}://root/output output || true
          result=`sshpass -p ${PASSWORD} ssh -o TCPKeepAlive=yes -o ServerAliveInterval=120 -o ServerAliveCountMax=9999 -o StrictHostKeyChecking=no -p ${PORT} ${USERNAME}@${HOSTNAME} "cat ./ubbd_test_result" || true`
          if [ "${result}" = "FAIL" ];then
            echo "FAIL"
            exit 1
          fi

          if [ "${result}" = "OK" ];then
            echo "OK"
            exit 0
          fi
          sleep 10
        done
