name: Run integration tests on ubuntu-20.04

on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: integration-tests
    steps:
    - uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add SSH key to known_hosts
      run: ssh-keyscan datatravelguide.yds.life >> ~/.ssh/known_hosts

    - name: executing remote ssh commands using password
      uses: datatravelguide/ssh-action@v0.1.10
      with:
        host: "datatravelguide.yds.life"
        username: ${{ secrets.SSH_USERNAME }}
	key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: whoami
      
    - name: SSH into server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SECRET_TEST: ${{ secrets.SECRET_TEST }}
        VAR_TEST: ${{ env.VAR_TEST }}
      run: |
        echo "secrets.SSH_PRIVATE_KEY: "
        echo $SSH_PORT_ENV
        echo $SSH_PRIVATE_KEY
        echo $VAR_TEST
        echo $SSH_PORT
        echo $SSH_PRIVATE_KEY > priv_key
        cat priv_key
        ssh -i ./priv_key  -p $SSH_PORT $SSH_USERNAME@datatravelguide.yds.life "echo 'Hello, world!'"

